### ISSUE TITLE
Add ability to add unlisted securities

### ISSUE THREAD

**Issue by nmjensen** [ghostfolio/ghostfolio#1352]
Hi there,

I've just started using Ghostfolio, and think it has a lot of potential!

I was loading my activities for the past couple of years, and one of my holdings (UWL.AX) has since been delisted due to being acquired. Because it's not a currently listed security, I can't add it.

Is there a way to include unlisted securities? Even if you have to put in the details manually?

Cheers,

Nick

**Comment by winklevos** [comment]
Also have this requirement, would be great

**Comment by Trentflix** [comment]
Would also appreciate this ability.

**Comment by JPFrancoia** [comment]
Same here. I am invested in a fund that isn't listed on Yahoo finance, Ghostfolio can't find info/prices and therefore I can't add activities. I'd like this feature too :)

**Comment by machinekoder** [comment]
Same here. What's missing is a UI dialog to add a custom market data entry with a custom symbol and then one could add the values by hand.

**Comment by MarcoCaneve** [comment]
Same here. That's the main feature that blocks me from using Ghostfolio. 
What is missing is the ability to add custom securities, for example at the moment users can't track:

- Bonds
- Rents
- Founds
- Investiment certificate and so on

of course since these are not tracked all the values (price, dividends, etc) must be added by hand

**Comment by dantrauner** [comment]
+1 as an easy workaround, though it would be nice to have bonds (even just US Treasuries).

**Comment by cromelex** [comment]
Just to add my support for this requirement.

I've tried ghostfolio but my pension fund invests in a non-listed fund. There is currently no way for me to track it, and thus it renders ghostfolio somewhat useless due to my inability to track it.

I'd be happy with the ability to manage this manually.

**Comment by dtslvr** [comment]
Thank you for bringing this up again, @cromelex.

This functionality has been available for some time. I have just made a PR (https://github.com/ghostfolio/ghostfolio/pull/3326) that extends the FAQ by custom assets.
