### ISSUE TITLE
Is it possible to represent a stock split?

### ISSUE THREAD

**Issue by dkarter** [ghostfolio/ghostfolio#1693]
Thank you for this awesome app! :)

I've been slowly trying to populate my transactions from Robinhood but not sure how one should go about representing a 3 for 1 forward split in Ghostfolio. 

One example of this is what happened with Tesla last year 

![image](https://user-images.githubusercontent.com/551858/218381267-aecbcc0a-eac9-4703-99fe-9afb099b1498.png)

Is this supported or are there any workarounds?

Edit: maybe the obvious solution is to create a sell of one unit on that date and a buy of 3 units at the historical price. 

Edit 2: Yea that worked nvm lol

**Comment by dtslvr** [comment]
> Yea that worked

That's it! 👍 In case the split happens now, you also need to refetch the (adjusted) historical data.

**Comment by LarsNorgaard** [comment]
Would still love, if we could add a --SPLIT-- line and then have the activities before that line have 3:1 split etc.

**Comment by MatanRubin** [comment]
I'm not sure if selling+buying achieves the same thing as actually representing a split. Specifically, it messes with the performance and investment numbers.
Here's an example - I bought 10 TSLA shares in 04/08/2014 for 216USD, my total investment was 2160USD.
TSLA shares have since been split twice at 3 to 1 and 5 to 1. After the splits, I should have 150 shares, but my initial investment hasn't changed. If I model this in ghostfolio as selling everything right before the split and then buying everything right after the split, my initial investment is now the price at which I bought after the split. This skews the performance metric to because the baseline in now at the split.

What's the best way to get the "real" performance metrics? Should I changed my activities before the split as if they happened after the split?

**Comment by dtslvr** [comment]
@MatanRubin see here #1072.

**Comment by MatanRubin** [comment]
Thanks, @dtslvr .
So basically the answer to this: 

> Should I changed my activities before the split as if they happened after the split?

Is "Yes". Right?
