### ISSUE TITLE
Importing dividends doesn't work - VDHX [BUG]

### ISSUE THREAD

**Issue by dojoca** [ghostfolio/ghostfolio#2240]
I've added my investment activities, and I am trying to import the associated dividends. 

I've added VDHG.AX, with activities starting back in 2019. When I try to use the "Import dividends" button (next to the "Import Activites" page), the window pops up for me to select a holding. 

I select the holding VDHG.AX, and click next. 

The next window shows nothing. Import button is greyed out. 

Logs reflect this error:

> [Nest] 142  - 08/15/2023, 8:02:12 AM   ERROR [YahooFinanceService] Could not get dividends for VDHG.AX (YAHOO) from 2019-11-24 to 2023-08-15: [Error] No newlines in: Date,Dividends

**Comment by dtslvr** [comment]
Hi @dojoca

This is expected behaviour as _Yahoo Finance_ does not provide historical dividend data for `VDHG.AX`, please [see here](https://finance.yahoo.com/quote/VDHG.AX/history?period1=1640995200&period2=1692057600&interval=capitalGain%7Cdiv%7Csplit&filter=div&frequency=1d&includeAdjustedClose=true).

To make it easier for us to assist you, please consider using our bug report template for any future issues. Thanks!
