### ISSUE TITLE
Action menu hidden in activities table

### ISSUE THREAD

**Issue by kurld** [ghostfolio/ghostfolio#2368]
Since updating from 1.3 to 2.4 there is no way to edit Activities. The three dots menu next to each activity, that was available in 1.3, is now gone.

**Comment by kurld** [comment]
Found a reason for that issue - if account name is 8 characters or more (at least on my screen) - Activity menu ( 3 vertical dots) in the activities view get truncated / is not visible.

**Comment by dtslvr** [comment]
> if account name is 8 characters or more (at least on my screen) - Activity menu ( 3 horizontal dots) in the activities view gets truncated / is not visible.

Can you show a screenshot?

**Comment by kurld** [comment]
![screen](https://github.com/ghostfolio/ghostfolio/assets/9458921/e701a498-ec80-4b62-bae0-0d60b1eb7e8c)
![screen2](https://github.com/ghostfolio/ghostfolio/assets/9458921/4d2b865e-37e5-482a-97b3-db22f2a21f08)

**Comment by kurld** [comment]
Actually it doesn't matter which filed is a long one, can be Name, or Quantity or other. If the row reaches certain width menu dots get truncated.

**Comment by Teonyr** [comment]
Just for the record, it's not just the dots getting hidden, as you can see in my screenshots, a lot of information is missing, because table display isn't wide enough.

I've been wondering for quite some time now, how to edit or delete activities and found no clue until I now discovered this github issue. 😵‍💫

All I see when opening my activities:
![Table not wide enough](https://github.com/ghostfolio/ghostfolio/assets/75175693/258d3683-60fd-448b-ba9a-5363d7f4e2cb)

If I scroll the table to the right (by clicking mouse wheel and dragging in Firefox):
![All that is hidden](https://github.com/ghostfolio/ghostfolio/assets/75175693/afa7dfd8-1ec9-4de2-b5e4-62c91bd96715)

**Comment by kurld** [comment]
That just makes me wonder how many Ghostfolio users don't even realize that they can edit and delete activities.

**Comment by pimterry** [comment]
I just ran into this - I didn't realise it was possible to edit activities until I found this issue and then the scrollbar!
