### ISSUE TITLE
Change create button in Access to Material Floating Action Button

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2447]
Remove the _Add Access_ button from `gf-access-table` (see _My Ghostfolio_ > _Access_) and add a `mat-fab` button to `gf-user-account-access` instead.
There is a very similar example in _Admin Control_ > _Market Data_.

![create-account-access](https://github.com/ghostfolio/ghostfolio/assets/4159106/1f2fcbfe-823c-4bd3-91e6-535ce09f88cd)

**Comment by akhil-pragallapati** [comment]
@dtslvr I would like to work on this issue, could you assign this to me.

**Comment by dtslvr** [comment]
> I would like to work on this issue, could you assign this to me.

Yes, sure!

**Comment by Tomkndn** [comment]
I think this issue doesn't exists below screenshot is attached.
![image](https://github.com/ghostfolio/ghostfolio/assets/105445488/91f27a5b-3d05-4da0-b0ca-c71315c0fbe3)

**Comment by dtslvr** [comment]
> I think this issue doesn't exists below screenshot is attached.

Yes, because the _Demo_ user does not have the permission to grant an access.

**Comment by akhil-pragallapati** [comment]
I am not able to proceed further, @dtslvr  unassigning the issue from my name.

**Comment by thesanjeevsharma** [comment]
Sorry for jumping onto this issue thread but I couldn't resist.

I see that the issue was assigned to some other contributor but @Dhoni77 created a PR directly. I can understand that everyone wants "the green graph" but please follow the right ethics. This behaviour can push away new contributors.

[Here's an article that might help](https://www.freecodecamp.org/news/how-to-contribute-to-open-source/#:~:text=Wait%20until%20the%20maintainer%20replies,end%2C%20create%20a%20pull%20request.)
> One of the essential ethics in open source is asking for the maintainer's permission to work on an issue unless stated otherwise in the contribution guide.

@dtslvr I'd be more than happy to add a `CONTRIBUTING.md` if you allow me to. :)

_(I am not a maintainer of this project / I do not represent ghostfolio; my views only)_

**Comment by Dhoni77** [comment]
Hi sorry @akhil-pragallapati for taking up the issue next time will ask the assigned person before taking up the issue in my name. 
Thanks @thesanjeevsharma for highlighting this👍.

**Comment by dtslvr** [comment]
> This behaviour can push away new contributors.

I agree with you @thesanjeevsharma. In this case, things fortunately sorted themselves out.

> @dtslvr I'd be more than happy to add a CONTRIBUTING.md if you allow me to.

I've been thinking about it too, but I'm hesitant because I'm not a fan of lengthy guidelines. Do you have a concrete file `CONTRIBUTING.md` from another project in mind?
