### ISSUE TITLE
[BUG] "Interest" activity doesn't update the value of the account

### ISSUE THREAD

**Issue by JPFrancoia** [ghostfolio/ghostfolio#2703]
**Bug Description**

When adding an activity of type "Interest" to an account, the total value of the account isn't updated.

**To Reproduce**

1. Create a random account
2. Add an activity of type "interest", and of value $100
3. Look at the account value: it's $0

**Expected behavior**

After adding the activity of type "Interest", I would expect the value of the account to increase.

**Additional context**

I am aware the "Interest" feature is experimental.
I'm using Ghostfolio 2.26.0 deployed on k8s cluster.

**Comment by dtslvr** [comment]
Your use of the workarounds does not seem to be ideal.

Interest currently works in a similar way to dividend. You can track it to know how much you have received in total. But it has no influence on the account cash balance (which you have to update manually).
Liabilities are also added up and additionally used to calculate net worth.

In order to correctly represent your use case, there is probably no way around introducing types for deposit and withdrawal. However, this would mean a major adjustment and would also affect the current concepts.

**Comment by JPFrancoia** [comment]
How would you track cash investments @dtslvr ?

**Comment by dtslvr** [comment]
> How would you track cash investments @dtslvr ?

You can update the cash balance of an account to track the progress over time. A new data point is created each time you update it.

**Comment by JPFrancoia** [comment]
> You can update the cash balance of an account to track the progress over time. A new data point is created each time you update it

I didn't know that, thank you. I can't update the entries through the UI, but I can go through the DB. So it should work for me, overall.

If you could add the ability to update the cash entries and/or update cash balance for interests, I think that would help the users.

**Comment by ar0311** [comment]
Same problem with dividends? Why is this greyed out?
