### ISSUE TITLE
Extend API for WTD and MTD date ranges

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2900]
Support `WTD` ("Week to date": start of Monday) and `MTD` ("Month to date": start of month) as date ranges by extending `getStartDate()` of `apps/api/src/app/portfolio/portfolio.service.ts`, `apps/api/src/app/user/update-user-setting.dto.ts` and `libs/common/src/lib/types/date-range.type.ts`.

**Comment by meuter** [comment]
Hi, thanks for creating the ticket and giving some pointers. It's been a while since I did any Typescript, but I am willing to give this one a try 😅 

I am a bit puzzled though. I am currently hosting a "production" instance of ghostfolio on my docker host in my homelab using the `latest` tag (I updated the container this morning to be sure) and in that version there is a small icon in the upper right corner that allows to open the date range panel:

![image](https://github.com/ghostfolio/ghostfolio/assets/843867/9e514fe1-d623-4cd4-aa86-e5244cfe6d8b)

leading to:

![image](https://github.com/ghostfolio/ghostfolio/assets/843867/d1d73fe2-6d97-41c9-822c-d116cb668a11)

However, when I use the latest version from `master` (as per the `Development` section of the README) I see the buttons at the bottom of the `Overview` page like in older version of the docker version.

![image](https://github.com/ghostfolio/ghostfolio/assets/843867/818f8751-b084-406c-ad1a-040a637c6c6f)

I suspect I am either (1) not using the right version of the docker container or (2) not using the right branch in git when running it from source. Do you know what's going on?

Thanks!

**Comment by dtslvr** [comment]
Hi @meuter

This is related to the _Experimental features_ setting in _My Ghostfolio_.

Great you give it a try. By the way in this first step, you can just extend the API (backend only).

**Comment by meuter** [comment]
Ah yes indeed, I turned that a while back, I was wondering what it did.

Already some progress 😄 
![image](https://github.com/ghostfolio/ghostfolio/assets/843867/19cea335-9899-42fd-8c0c-d5a44ebf4d1d)

As soon as I have something ready, I'll create a PR for review.

Thanks again for the help!

**Comment by meuter** [comment]
As you suggested I created a PR focusing on the back-end first. Let me know what you think.
