### ISSUE TITLE
Is the `watch:server` script correct?

### ISSUE THREAD

**Issue by I-Valchev** [ghostfolio/ghostfolio#328]
Hey! On my local setup, the `watch:server` yarn script doesn't seem to work properly.

With `nx build api --watch`, the client side app cannot connect to the servier. Updating this to `nx serve api --watch`, which I took from nx docs, seems to fix it.

Is it something I'm doing wrong?

**Comment by dtslvr** [comment]
Hello @I-Valchev

I'm using `yarn watch:server` to just watch the api build, not to "serve the server". I'm running it with _Visual Studio Code_ (See here: https://github.com/ghostfolio/ghostfolio#start-server).

What do you think about adding `--watch` here https://github.com/ghostfolio/ghostfolio/blob/main/package.json#L39 instead of your proposal?

**Comment by I-Valchev** [comment]
@dtslvr that works too! 👍

**Comment by dtslvr** [comment]
> @dtslvr that works too! 👍

Are you using `nx serve api --watch` now and is it working as expected? If yes, would you mind creating a PR?
