### ISSUE TITLE
Add new currency and stocks from another country

### ISSUE THREAD

**Issue by eHonnef** [ghostfolio/ghostfolio#386]
I really enjoyed this project, it's simple and very intuitive and the best one is that it is open source and self hosted :D

But I can't use to manage the portfolio on my country (Brazil), I don't know the technical details, but I think it'll not be so difficult to add the B3 (Bovespa and BMF) and BRL currency to the project, the stock info already is at the yahoo financial (for example PETR4).

Thanks and keep the good work :D

**Comment by dtslvr** [comment]
Thanks a lot for your feedback @eHonnef.

At the moment, [Ghostfol.io](https://ghostfol.io) only supports the following currencies: `CHF`, `EUR`, `GBP` and `USD`.

To support unlimited currencies, there is some rework needed:

1. Migrate the database schema from `enum` to `string`
2. Adapt code (`enum` to `string`)
3. Dynamically identify the currencies needed (user accounts, accounts, transactions)
4. Allow to set the base currency in _My Ghostfolio_

This issue is related to #286 (symbol in `CAD`) and I have just started to work on it.

**Comment by eHonnef** [comment]
Thanks, I'm looking forward to use it :D

**Comment by dtslvr** [comment]
> Thanks, I'm looking forward to use it :D

I have started working on it here #387. It's still a draft and needs some more refinements.

**Comment by dtslvr** [comment]
I have merged this feature now. Do you have a chance to check it and give feedback @eHonnef?

Do not forget to regenerate database typings (`database:generate-typings`) and apply the data migration (`yarn prisma migrate deploy`).
