### ISSUE TITLE
[BUG] Error: EACCES: permission denied, open '/ghostfolio/entrypoint.sh'`

### ISSUE THREAD

**Issue by viktor-sc** [ghostfolio/ghostfolio#3946]
**Bug Description**

Container not starting after update to latest version.
Error: EACCES: permission denied, open '/ghostfolio/entrypoint.sh'`

**To Reproduce**

1. Self hosted on a Synology (Container Manager)
2. Update from 2.115.0 to 2.116.0
3. Start Container and see logs. Container stops automatically again.

**Expected behavior**

No error

**Logs**

`Node.js v20.18.0

}
  path: '/ghostfolio/entrypoint.sh'
  syscall: 'open',
  code: 'EACCES',
  errno: -13,
    at node:internal/main/run_main_module:28:49 {
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._extensions..js (node:internal/modules/cjs/loader:1504:19)
    at getMaybeCachedSource (node:internal/modules/cjs/loader:1492:18)
    at Object.readFileSync (node:fs:448:20)
Error: EACCES: permission denied, open '/ghostfolio/entrypoint.sh'

                   ^
    return binding.readFileUtf8(path, stringToFlags(options.flag));
node:fs:448
Node.js v20.18.0

}
  path: '/ghostfolio/entrypoint.sh'
  syscall: 'open',
  code: 'EACCES',
  errno: -13,
    at node:internal/main/run_main_module:28:49 {
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._extensions..js (node:internal/modules/cjs/loader:1504:19)
    at getMaybeCachedSource (node:internal/modules/cjs/loader:1492:18)
    at Object.readFileSync (node:fs:448:20)
Error: EACCES: permission denied, open '/ghostfolio/entrypoint.sh'`

**Environment**

Self hosted on a Synology NAS.

- Ghostfolio Version 2.116.0
- Self-hosted
- Experimental Features disabled
- Browser. Chrome

**Comment by dtslvr** [comment]
This is related to #3903. Any idea what is happening @jnbrisset?

**Comment by steffenrapp** [comment]
I have the same issue on Synology with Portainer.

**Comment by jnbrisset** [comment]
There are 3 security options in the docker-compose.yml file which are not present in the docker-compose.build.yml. Removing those fix the issue, although I have to read more on docker compose security_opt to an advisable solution. 

Those below, if commented out, docker compose with docker-compose.yml works again.

```
    security_opt:
      - no-new-privileges:true
```

Suggestions are welcome. I'll try to see what I can come up as a proposition.

**Comment by steffenrapp** [comment]
Removing `security_opt:` didn't help me but after moving `user:` from ghostfolio to redis the container started properly even with `security_opt:`.

**Comment by asiananimal** [comment]
In https://github.com/ghostfolio/ghostfolio/pull/3903 /ghostfolio/entrypoint.sh was chmod to 0700. Thus any user other than the owner of the file can not read/write/execute the file. I'm running into this bug at 2.116.0 and beyond because I'm running the ghostfolio stack with a different user than the default (I believe the default user is 999 or nobody). I suspect that if we change the chmod to 0755 it should allow the user specified by the docker compose file to also execute /ghostfolio/entrypoint.sh

**Comment by dtslvr** [comment]
@jnbrisset @steffenrapp @viktor-sc What do you think about https://github.com/ghostfolio/ghostfolio/pull/3971?

**Comment by asiananimal** [comment]
@dtslvr 

I believe that #3971 should fix this issue with the smallest change footprint.

However, if Ghostfolio wants to support custom PUID and PGID, I believe the more robust change would be to do the following.

1. Add a `ghostfolio` user and `ghostfolio` group in the `Dockerfile`. See the following example https://github.com/Tautulli/Tautulli/blob/master/Dockerfile#L14-L15

2. Then inside the `ENTRYPOINT` script (in ghostfolio it would be `/ghostfolio/entrypoint.sh` in the example it is `./start.sh` We would take the specified PUID/PGID in docker-compose and effectively change the `ghostfiolio` PUID created in step 1 to the docker-compose PUID, same would be done with PGID. See the following example https://github.com/Tautulli/Tautulli/blob/master/start.sh#L4-L8

3. Finally, we would chown all the files in the ghostfolio files to ghostfolio:ghostfolio created in step one and would match the PUID/PGID specified in docker-compose because of what we do in step 2. See example https://github.com/Tautulli/Tautulli/blob/master/start.sh#L10

As you can see, this is something a bit more involved and risky of a change than my proposed changes. However, this change is more robust in support for user defined PUID/PGID. I would a change in the future which will do what's listed in this comment, but with much more discussion on how it would effect devs/users.

**Comment by ymage** [comment]
The issue is that to perform a 'chown', the container must be run with root privileges at startup. 
Any solution using PUID/GUID as an environment variable cannot work if the container starts without root privileges.

**Comment by asiananimal** [comment]
@ymage You are correct in that the default docker user does have root like privileges and therefore can chown files. That default user and group id is 1000 and name `node` in ghostfolio's case. The trick in what I described above is to start the container not by using the following compose file

```
services:
  ghostfolio:
    image: docker.io/ghostfolio/ghostfolio:2.115.0
    user: 9999:9999
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
....
```

This will start the container using 9999 which like @ymage said does not have root privileges at startup and therefore can not chown files. This can work today almost as with the exception of entrypoint.sh being 0700 which doesn't allow for 9999 to start the file and thus my change #3971 

However, the more robust way of supporting custom PUID and PGID is to start ghostfolio like this:

```
services:
  ghostfolio:
    image: docker.io/ghostfolio/ghostfolio:2.115.0
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
...
```

This will still start the container with user 1000 with root like privileges. With these privileges you can change your own uid/gid to the one specified in the environment vars as described in step 3 of the above.

```
    PUID=${PUID:-1000}
    PGID=${PGID:-1000}

    groupmod -o -g "$PGID" node
    usermod -o -u "$PUID" node
```

At this point you can still chown files to the new PUID/PGID since you still have root like privileges. Finally you would run something like 

```
su node -g node -c "aScriptThatDoesWhatEntrypointShDoesToday"
```

This will execute the script that does what `ghostfolio/entrypoint.sh` does today but under node user and node group, which now matches the env specified PUID and PGID because of the `groupmod` and `usermod`. From this point on you will not run as a user that has root like privileges and under a user/group specified by the user.

Why go through this trouble?

1. You don't want to run the bulk of ghostfilio under a user that has root like privileges. I doesn't need root as far as I can tell and would be safer to have the lowest amount of privileges as possible.

2. While today ghostfolio doesn't mount a docker volume, it may want to someday. If that day comes, being able to run as a specified user/group will allow the volume to be backed by NFS which has very strict read/write/execute based on user/group ids. Furthermore, the user may want the files to be owned by a specific user to restrict who can read the files on the same system of the volume mount.

**Comment by asiananimal** [comment]
One last point, the change in #3971 allows the user to start ghostfolio as any other user as reported by @viktor-sc , however, if we implement what I described above to more robustly support PUID and PGID. You will no longer need #3971 and would want to revert back since you would be able to chown the entrypoint the the specified PUID and PGID and therefore not need read/execute by other users.

**Comment by ymage** [comment]
If I understand correctly, the container starts with the node user, who then changes its own UID and GID?
 Is it really possible to change one's own UID and GID without being root?

**Comment by asiananimal** [comment]
@ymage Ghostfolio starts with the user name node (uid=1000,gid=1000) this user has root like privileges and thus can run the following commands to change his own uid/gid to any id.

```
    PUID=${PUID:-1000}
    PGID=${PGID:-1000}

    groupmod -o -g "$PGID" node
    usermod -o -u "$PUID" node
```

Yes it is possible, have you click through to the example links that I've listed before that shows this? I've even highlighted the lines that shows this example. The example of this is in a project that has more stars and forked more times than ghostfolio.

https://github.com/Tautulli/Tautulli/blob/master/start.sh#L4-L13

Let me know which part of the example isn't clear.

**Comment by asiananimal** [comment]
@dtslvr https://github.com/ghostfolio/ghostfolio/pull/3992 is a draft proposal to support for PUID / PGID.

#3971 fixes this issue if you want to keep the change surface much smaller.

**Comment by viktor-sc** [comment]
Hey guys, is there a quick workaround for me until the final solution gets implemented?

**Comment by chaelli** [comment]
@viktor-sc just remove / comment the user: .. part of the main container

**Comment by jnbrisset** [comment]
I’ve been busy the last two weeks, hence my absence of the discussion. It seems to generate an issue for most users. I suggest that we remove it as well.

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Michael Keller ***@***.***>
Envoyé : Friday, November 1, 2024 10:23:42 AM
À : ghostfolio/ghostfolio ***@***.***>
Cc : JN Brisset ***@***.***>; Mention ***@***.***>
Objet : Re: [ghostfolio/ghostfolio] [BUG] Error: EACCES: permission denied, open '/ghostfolio/entrypoint.sh'` (Issue #3946)


@viktor-sc<https://github.com/viktor-sc> just remove / comment the user: .. part of the main container
