### ISSUE TITLE
Add support for free stocks

### ISSUE THREAD

**Issue by lsrom** [ghostfolio/ghostfolio#521]
When I add stock with price "0" overview does not load and console spits out errors:

```
ghostfolio_1  | [Nest] 1  - 12/07/2021, 5:03:29 PM   ERROR [ExceptionsHandler] [big.js] Division by zero
ghostfolio_1  | Error: [big.js] Division by zero
ghostfolio_1  |     at Big.P.div (/ghostfolio/apps/api/node_modules/big.js/big.js:356:13)
ghostfolio_1  |     at PortfolioCalculator.<anonymous> (/ghostfolio/apps/api/main.js:3735:62)
ghostfolio_1  |     at Generator.next (<anonymous>)
ghostfolio_1  |     at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:114:62)
ghostfolio_1  |     at runNextTicks (internal/process/task_queues.js:60:5)
ghostfolio_1  |     at processImmediate (internal/timers.js:437:9)
```

Running in docker built from v1.86.0 tag.

**Comment by theghostofc** [comment]
Current functionality works when trying to add stocks with "0" price. Tried with both - 1. create activity and 2. import CSV - in v1.221.0

**Comment by dtslvr** [comment]
> Current functionality works when trying to add stocks with "0" price.

Great, thanks a lot for your feedback @theghostofc.

**Comment by gstr3745** [comment]
I'm sorry to re-open this thread, but I'm facing a little issue with free stocks:
![immagine](https://github.com/user-attachments/assets/afc3c44a-6e50-45fb-a44a-f5191c614c89)

The graph shows spikes whenever I insert a free stock buy, setting for that day the value of the entire asset to 0.
Is there a way to force it, taking the market value, instead of the manual value I inserted?

I tried importing csv values for the asset, in the market data section, but still the 0 price value overrides the other.
I also tried to insert some placeholder transaction (buy and sell) at market value, after the free stock transaction, but still the 0 value overrides the other ones...

**Comment by gstr3745** [comment]
Hi, I think I'm the only one bothered by these spikes, but I found a workaround which actually works 😄 

![Image](https://github.com/user-attachments/assets/3f419626-6ff1-473d-b214-ef85b8791b87)

Adding a buy and a sell activity before and after the free stocks, as shown in the picture, prevents the graph from showing the spikes.
Hope this could be useful for others.
