### ISSUE TITLE
How to for the Finalization part

### ISSUE THREAD

**Issue by simple-it** [ghostfolio/ghostfolio#635]
I don't know how to perform the 2 following steps:

1. Assign the role ADMIN to this user (directly in the database)
2. Delete the original Admin (directly in the database)

Can it be explained?

**Comment by dtslvr** [comment]
Hi @simple-it

* Connect to your database with a proper tool. I'm using [pgAdmin](https://www.pgadmin.org) for it.
Then find the table `User` and the row you would like to edit. In the column `role`, change the value from `USER` to `ADMIN` (1.)
* After that you should have two users with the role `ADMIN`. You can delete the older one (2.)

**Comment by simple-it** [comment]
But pAdmin or other client are not allowed to connecting to DB.

I don't have xp in Docker and Postgres but I know for MySQl server before external connection I ve to allow that.

Maybe I ve to configure in the Postgres Docker?

**Comment by juic3pow3rs** [comment]
You can also use psql to accomplish that. 
Assumptions:
* you used the docker-compose.yml and .env in this repo
* you only created **one** user after successful startup of ghostfolio

<br />
Enter the psql shell within the postgres container:
```docker-compose exec postgres psql -U user```

Update the role of the new user to ADMIN:
```UPDATE "User" SET  "role" = 'ADMIN WHERE "provider" =  'ANONYMOUS';```

Delete the original ADMIN user:
```DELETE FROM "User" WHERE "alias" = 'Admin' ```

Exit the psql shell with:
```\q```

<br />
<br />

Note: 
The double quotes are necessary because of the mixed case column names.
If you have more than one user you would need to use the id of the user to want to grand ADMIN permissions in the WHERE clause,

**Comment by dtslvr** [comment]
Thank you very much for these instructions @juic3pow3rs! 👍🏻
