### ISSUE TITLE
Can not edit currency of activity

### ISSUE THREAD

**Issue by narcoleptic568** [ghostfolio/ghostfolio#705]
Hi,

first of all, I would like to thank all you guys who put effort in creating this great tool.

I just started using ghostfolio and wanted to add my previous activities to my portfolio. As I understand, the currency for an activity is determined by the currency of the chosen symbol. In my case however, most transactions are made through european brokers in euros, even when the symbol's original currency is dollar. Currently, i would need to manually convert the prices of those transactions from euros to dollars in order to add them to my activities. In the end, ghostfolio would convert them back as I have my portfolio shown in euro as base corruncy.

Could you add the functionality to manually adjust the currency of an activity?

**Comment by sts0210** [comment]
I think this is a must have for most non-US users. I use different brokers in Germany and all of them calculate prices only in EUR, so basically, adding activities is currently a pain in the butt and the only workaround is to set currency to USD everywhere and just mentally substitute USD with EUR everywhere...

**Comment by casitu** [comment]
Indeed, this is now the major issue for users. If your base currency is X (i.e_ EUR) or your account has eur as currency, no matter in what market stock is listed, prices and fees should be in your base currency or your account one.

I'd prefer the second option, because you could have two accounts in one broker: one in your base currency and one (or more) in a foreing one.

**Comment by cbirkenbeul** [comment]
Came across this issue and thought I made a mistake while setup. So please prioritize this feature request a bit. Thanks.

**Comment by IsusVonBier** [comment]
I think the best option would be to be able to choose manually currency when adding transactions.

**Comment by ymage** [comment]
I am stuck with this issue. 
I just can't convert my previous transactions from EUR to USD looking for each of them the conversion rate from the past

**Comment by casitu** [comment]
To me, this is the most pressing issue to resolve, as stated in #789.

**Comment by casitu** [comment]
Now that #789 is closed, I think it is time to face this issue with a similar workaround. If your base currency differs from the symbol's, base currency should take precedence. Or at least have a combo to change currency if desired.

**Comment by enviousjag** [comment]
As far as I can tell, this issue is a bit more complicated. It basically burns down to ghostfolio needing to support more brokers and multiple currencies. And please do correct me if I'm wrong. I'm just hammering out my thought here.

I was trying to test ghostfolio on how the input sheet for "Add Activity" works. For my example, I chose to set the base currency to EUR. I then selected a German ETF, based in Germany in EUR. -> [DE0005933931](https://www.justetf.com/en/etf-profile.html?query=DE0005933931&groupField=index&from=search&isin=DE0005933931)

I then went ahead and created a transaction using todays date and unit price, selecting the suggested  ETF Name DAXXF. 
The issue that immediately popped up was, that the lookup function decided to grab the ETF price from yahoo. And the ETF currency was changed to USD. 

So if ghostfolio want to support multiple currencies, one needs to disable the lookup function on the "Add activity" when adding Activities or one needs to be able to select the correct marketplace from which one bought the ETF, stock or whatever. The second option making more sense and enabling the performance & analysis features to continue working correctly. 

What do you guys think?

**Comment by dtslvr** [comment]
> I then went ahead and created a transaction using todays date and unit price, selecting the suggested ETF Name DAXXF. The issue that immediately popped up was, that the lookup function decided to grab the ETF price from yahoo. And the ETF currency was changed to USD.

Hi @enviousjag

I think you need to add the ticker `EXS1.DE` (instead of `DAXXF`) as mentioned [here](https://www.justetf.com/en/etf-profile.html?query=DE0005933931&groupField=index&from=search&isin=DE0005933931#listing) and the currency will be `EUR`.

**Comment by enviousjag** [comment]
Meaning, that I cannot rely on the suggested ETF/Stock but have to find the correct ticker? Doesn't seem all that intuitive but will report on progress later.

**Comment by enviousjag** [comment]
> 
> Hi @enviousjag
> 
> I think you need to add the ticker `EXS1.DE` (instead of `DAXXF`) as mentioned [here](https://www.justetf.com/en/etf-profile.html?query=DE0005933931&groupField=index&from=search&isin=DE0005933931#listing) and the currency will be `EUR`.

This did work indeed. Thanks for your help. 
I did run into another issue though... neither firefox or safari are respecting the locale set. Specifically using comma instead of dot for decimals.

**Comment by dtslvr** [comment]
> Meaning, that I cannot rely on the suggested ETF/Stock but have to find the correct ticker?

In some cases, it is not optimal. But there is not much you can do about it. This project depends on the data provided by the data source.

> This did work indeed. Thanks for your help.

Great! 👍🏻 

> I did run into another issue though... neither firefox or safari are respecting the locale set. Specifically using comma instead of dot for decimals.

Can you please open a new issue and fill out the bug report template @enviousjag? Thank you.
