### ISSUE TITLE
ETF sectors not reflected in Allocations page

### ISSUE THREAD

**Issue by jamiehannaford** [ghostfolio/ghostfolio#715]
When you add an ETF, for example `IS0D.DE`, it can be successfully added to a portfolio, but its respective sector and country breakdowns are not reflected in the `portfolio/allocations` page:

<img width="383" alt="Screen Shot 2022-02-20 at 14 57 34" src="https://user-images.githubusercontent.com/1867202/154846187-fe23f1a3-89ee-42ad-a430-3806847e52f2.png">

It would be awesome to show this in the graphs. I'm not sure if there's a site that can provide top-level metadata for an ETF - but another option could be finding its largest holdings and using those sectors to determine the parent ETF.

**Comment by jamiehannaford** [comment]
Another option here is to allow folks to manually specify the industry/sector when adding a ticker 🤔 Maybe that would be easier than trying to scrape the holdings of a given ETF.

**Comment by dtslvr** [comment]
Hi @jamiehannaford

There is already a data enhancer for the use case you are describing. The problem is that `IS0D.DE` could not be resolved automatically.

1. Go to https://www.trackinsight.com and search for "iShares Oil & Gas Exploration & Production"
2. Select your ETF (I guess it's https://www.trackinsight.com/en/fund/IEO)
3. Find the record with the symbol `IS0D.DE` in the `SymbolProfile` table of your database
4. Add the following to the `symbolMapping` column:
```
{"TRACKINSIGHT":"IEO"}
```
5. Open http://localhost:3333/admin/market-data, find the entry for `IS0D.DE` and click the _Gather Data_ action

Now you should have the sector and country data for your ETF.

**Comment by jamiehannaford** [comment]
That's awesome, thanks for the tip @dtslvr 👍
