### ISSUE TITLE
Overview - Today

### ISSUE THREAD

**Issue by wisobe** [ghostfolio/ghostfolio#779]
Hi,

First of all, this is a great tool. Amazing work. :-)

I seem to have an issue but I can't say if it's a bug or if it's due to my setup. Basically, I don't have any information for the "Today" view on the overview page. It gives me 0$ and 0%. If I go to the "Holdings" and choose the "today" view, once again all the companies show 0$ and 0%. Is this a normal behaviour ?

Thanks a lot

**Comment by dtslvr** [comment]
Thanks for your feedback @wisobe.

No, this isn't normal behaviour. It's most probably an issue with historical market data. Have you been able to set up the demo account successfully following these [instructions](https://github.com/ghostfolio/ghostfolio#fetch-historical-data)?

Do you notice any warnings in the console when you try load the overview?

**Comment by wisobe** [comment]
Hi @dtslvr,

Yes I've been able to setup everything as explained. I went to the demo site and you'll find attached a screenshot of the result. As you can see, one stock has updated information, the others are at 0. On my account, they are all at 0.

There were no warnings except the warning that it could take some time to gather all the data.

![Screen Shot 2022-04-01 at 8 41 38 PM](https://user-images.githubusercontent.com/70667278/161357380-e53be389-a4b2-42b6-a919-fe2a0c45e6fd.png)

**Comment by dtslvr** [comment]
As the title of this issue indicates, you have selected `1D` (Today). Then this is totally fine for me, because the markets for `AMZN`, `TSLA` and `VTI` are currently closed (see the pause icon).

You can open the last tab of the Admin Control Panel to check the historical market data of each symbol. If they are green, it's fine 🙂

**Comment by wisobe** [comment]
If the « today » button does not give me my gains or losses of the day, what is the use of this view ? Should I be forced to check the page before the markets close ?

**Comment by dtslvr** [comment]
No. Please check again on Monday, when the markets (were) open.

**Comment by wisobe** [comment]
Hi !

I connected to my environment today and indeed I see the gains or losses of the day. When markets close, it would be nice to keep the daily statistics static until the markets reopen the next day.

**Comment by dtslvr** [comment]
Thanks for coming back @wisobe.

I think it is exactly implemented as you describe:

<img width="410" alt="closed-market" src="https://user-images.githubusercontent.com/4159106/161617694-625b7126-3f31-44f4-b2f9-79e05dc074ae.png">

The market of `ALV.DE` is closed, but it still shows the daily statistics. On the next day, the gains and losses are reset, because I don't want it mixed with positions where the market is always open (cf. cryptocurrencies). You can check the demo account on [Ghostfol.io](https://Ghostfol.io).
