### ISSUE TITLE
Formal API for adding transactions

### ISSUE THREAD

**Issue by GT448** [ghostfolio/ghostfolio#782]
Hello!

I came across this tool recently, and have to say great work so far!
I'm wondering if there's any plans to support a formal API for submitting new transactions ("activities") programmatically?

I have an API integration with my broker, and I was thinking it would be cool to have trades and dividends automatically populated.

**Comment by dtslvr** [comment]
Hi @GT448

Thanks for creating this issue. We have an ongoing discussion in our [Slack community](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) about the same topic. I will post my thoughts about it here, because I think it's more suitable to discuss here.

From an architectural point of view I would start with a separate (micro) service which is able to connect to e.g. Interactive Brokers. Then, it converts the orders to the format Ghostfolio is able to handle and calls the import endpoint of the Ghostfolio instance. This way, it’s easier for community members to integrate other platforms and the Ghostfolio core stays maintainable for now.

The tasks I see are
* Create a micro service as described
* Document, expose and secure the already existing Ghostfolio import API
  * Support API tokens for technical users
  * Check for duplicate activities (do not import again)

What do you think of such an approach?

**Comment by GT448** [comment]
Hey @dtslvr,

Thanks for the prompt response!
This approach sounds perfect to me!

**Comment by dhishan** [comment]
I had the same question on slack @GT448, I have been looking at other platforms that can integrate with banks securely as an expansion to this. I found https://plaid.com/global/.

**Comment by dtslvr** [comment]
I have setup API versioning and refactored the parameters of the import endpoint. [Here](https://github.com/ghostfolio/ghostfolio#public-api-experimental) you can find the documentation.

Add the moment, you need to use your Bearer Token. In future, we can think of API tokens with restricted permissions.

Can you start working on your integration or is there something essential still missing? I would be happy to read your feedback.

**Comment by GT448** [comment]
I did not expect this to happen so fast! That's great, thank you!
I guess I had better get my broker API working then!

**Comment by dtslvr** [comment]
> I did not expect this to happen so fast! That's great, thank you! I guess I had better get my broker API working then!

Yes @GT448, go for it and tell us what you are building 😃

**Comment by a-waider** [comment]
Hi,
I tried to import my stock transactions into ghostfolio, but I can't get through the authorization. Could you push me into the right direction how to get an appropiate bearer token? I'm hosting ghostfolio myself via docker if that makes any differance.

**Comment by dtslvr** [comment]
> Hi, I tried to import my stock transactions into ghostfolio, but I can't get through the authorization. Could you push me into the right direction how to get an appropriate bearer token? I'm hosting ghostfolio myself via docker if that makes any difference.

Hi @a-waider

The bearer token is sent with each request while you have a login session. To get yours, you can inspect the network requests in your browser (e.g. via [Chrome DevTools](https://developer.chrome.com/docs/devtools/open)) and check `Authorization` from the _Request Headers_. The bearer token starts with `Bearer ey...`.
